### ISSUE TITLE
Error ENOENT when calling <model>.attach(...)

### ISSUE THREAD

**Issue by SeyZ** [heapsource/mongoose-attachments#22]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)
```

**Comment by SeyZ** [comment]
Ok, I found the problem. On my server, ImageMagick was not installed so it fails at: `im.identify` call in the `attach` function.

Maybe it can be useful to check if ImageMagick is correctly installed and handle the error if not?
